### ISSUE TITLE
Vcenter-exporter Unhandled error in Deferred:

### ISSUE THREAD

**Issue by tamilsaran** [kremers/charts-vmware-exporter#11]
Like I deploy the vmware-exporter helm char via and, I create the pod monitor in vmware-exporter but, i am facing below issue.

I check the vmware-exporter log

2022-09-21 11:22:18,358 INFO:Finished vm metrics collection
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1845, in _async_render_GET
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 286, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1080, in finish
    "Request.finish called on a request after its connection was lost; "
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

**Comment by kremers** [comment]
Hello tamilsaran,

Please refer to https://github.com/pryorda/vmware_exporter
You can try to increase the exporter version in the values configuration, to sort out connectivity problems.

Kind regards
  Martin

**Comment by kremers** [comment]
Closing this issue due to age, if its still present, please open a new one.
